### ISSUE TITLE
서비스 생성 관련 이슈들

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_composer#28]
## 남은 이슈들
* [x] 사용하지 않는 환경 변수 정리 (#30)
* [ ] 기존의 서비스 목록이 없는 경우, export 저장할 패키지 목록을 선택하지 못함 (#32)
* [x] 서비스 저장시 사용되는 repo 에서 무조건 master branch 만 사용하는것이 아니라 선택적으로 다른 branch를 사용할 수 있도록하고, 이를 설정하는 환경 변수 추가 (#33)
* [x] ```***.launcher``` 파일이름이  ```***.launch``` 로 변경되어야 합니다. 
* [x] launcher_type에 쓰는 값은 ros_launch 에서 roslaunch 로 변경되어야 합니다.
* [x] launcher 에는 다음과 같은 형식으로 저장 되어야 합니다. 서비스 매니저 쪽에서 확장자명을 붙여서 검색해 주기 때문입니다. 
```
launcher: <저장될 패키지 이름>/<서비스 이름>
(ex.  launcher : concert_common_services/chatter )
```
* [x] 위와 비슷하게 interactions, parameters 또한 같은 형태로 저장됩니다.
```
(interactions or parameters) : <저장될 패키지 이름>/<서비스 이름>
(ex. (interactions or parameters) :  concert_common_services/chatter )
```

* [x] workflow가 포함된 서비스를 export 할 경우 다음 사항이 추가되어야 한다. 
  * parameters에 아래 내용을 추가한다.
    
    ```
    workflows: <저장될 패키지 이름>/<서비스 이름>.workflows
    ```   
  * <서비스 이름>.workflows 파일을 만들고, 다음 내용을 작성한다.
    
    ```
    workflows:
      - workflow: <저장될 패키지 이름>/<체크한 워크플로우 1, 확장자명 포함 (new1_wf.wf) >
      - workflow: <저장될 패키지 이름>/<체크한 워크플로우 2, 확장자명 포함 (new2_wf.json) >
      .....
    ```
* [x] hic app 블럭이 포함된 워크플로우를 선택시, interactions 부분이 만들어지지 않는 문제 (#29)
* [x] parameters도 사용자가 임의로 추가하듯이( ```Add row``` 를 이용해 추가) interactions 에도 그러한 부분 추가
* [ ] 서비스의 dependency 추가 (#31)
* [x] 서비스 생성시 remapping 정보를 workflow에 포함하는 기능 (#34)
* [x] 같은 서비스 이름으로 export 할때, package.xml 에 중복되어 export 되는 경우 #35

**Comment by eskim** [comment]
> 기존의 서비스 목록이 없는 경우, export 저장할 패키지 목록을 선택하지 못함

이 부분은 즉, 기존 서비스 목록이 없는 경우는 어떻게 처리를 해야 하나요?

**Comment by eskim** [comment]
> 사용하지 않는 환경 변수 정리

환경 변수는 config 파일과 파라미터로 처리하기로 했는데 별도의 이슈로 정리해 주실수 있나요?

**Comment by dwlee** [comment]
이슈 목록에 계속 업데이트를 진행하도록 하겠습니다.
